[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "zlib", "libjpeg", "libpng", "libgl1"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8001}"
